version: '3.8'

services:
  api:
    image: ${DOCKER_REGISTRY-}product.api
    container_name: api
    build:
      context: .
      dockerfile: Product.Api/Dockerfile
    ports:
      - "8080"
      - "8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${ASPNETCORE_Kestrel__Certificates__Default__Path}
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${ASPNETCORE_Kestrel__Certificates__Default__Password}
      - ConnectionStrings__DefaultConnection=${ConnectionStrings__DefaultConnection}
    depends_on:
      - database
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    networks:
      - global.network

  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: database
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_PID=${MSSQL_PID}
    ports:
      - "1433:1433"
    volumes:
      - global.data:/var/opt/mssql
    networks:
      - global.network

volumes:
  global.data:

networks:
  global.network:
    driver: bridge
