name: .NET Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies
        run: dotnet restore Product.Api.sln
      - name: Build
        run: dotnet build Product.Api.sln --configuration Release
      - name: Save Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            bin/Release/net8.0/*

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
      - name: Run Tests
        run: dotnet test Product.Api.sln --configuration Release --verbosity normal --logger "trx;LogFileName=test_results.trx"
