name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies for all projects
      run: dotnet restore ./Product.Api.sln
    - name: Build
      run: dotnet build ./Product.Api.sln --no-restore

  tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Test
      run: dotnet test ./Product.Api.sln --no-build --verbosity normal

  publish:
    runs-on: ubuntu-latest
    needs: [build, tests]
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Publish
      run: dotnet publish ./Product.Api.sln -c $ASPNETCORE_ENVIRONMENT -o ./publish

  upload:
    runs-on: ubuntu-latest
    needs: publish
    steps:
    - name: Upload publish artifacts
      uses: actions/upload-artifact@v3
      with:
        name: publish-artifacts
        path: ./publish
