name: .NET Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies
        run: dotnet restore Product.Api.sln
      - name: Build
        run: dotnet build Product.Api.sln --configuration Release --output ./output

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Run Unit Tests
        run: dotnet test Product.Api.UnitTest/Product.Api.UnitTest.csproj --no-build --configuration Release --verbosity normal --logger "trx;LogFileName=test_results.trx"
      - name: Run Integration Tests
        run: dotnet test Product.Api.IntegrationTest/Product.Api.IntegrationTest.csproj --no-build --configuration Release --verbosity normal --logger "trx;LogFileName=test_results.trx"
